os: linux
language: node_js
node_js:
- '14'
dist: xenial
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless
notifications:
  email: false
  slack:
    secure: EZnH+w/FhlksJ6tPVd11XYpV5LViL47I0V1tMv2ak/CBJItzklHNtjbAr5s3Rf9TvhCPZ7KuvrhiKM/zWqprLLCCVKKD/GwUmjTVRn7Qqu4h3nkHNRE92liKO1l4OJmzELk55geXu3RSEpSQeysA9fcdK6/wEEk1BnjtYZ6WyYjwQtBkrUIOWOHVygEYBn194HDrQ2Gb0RwjJsVQUNvVDAHsaDQcXWCqGE7SAflC1TPEVGDxcz0zsItPJORmLucM2P48HxiF3huf58+vkGAuLXPHvspxsqdbMMVYTfZQqNBsinZAao0Z4IjD9ivDpZE22qYRLwq4HP0/Gs9kgXkIhXMHf+Ztpho+eCVlySytzlzvOb/EpiMDWokksfcf9Iq2DS+ji8utQDzSm43B77xQJa6CiraASlu+zmLjw1geJ2SFM90aRr1cjDlcwnQtL4ivJABPIooj4s/uoxYypgyGIaKWhFHAyRRtSeC30YDvR2L3kVhXhBGMpV2aZAEDQad8KKvcNylTlnLQCmE9gRSLB1gMdusmiawfkgUEsNOlM7chy770r9NlXEFJ5k0fZcrkcXX6vcORvMnEypp+4Fbo0Hj2Mhu1p1BBkX+Eb0v5fW0vT7ZrlV6c9WVHk8X9FsXhyRLWG08czTbAIzLiSp9B1pu0GMxsbEI0HPIZ+IWKLKk=
