os: linux
language: node_js
node_js:
  - '14'
dist: trusty
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
