languaje: node_js
node_js:
  - "14"
dist: trusty
sudo: required

branches:
  only:
    - master

before script:
  - npm install -g @angular/cli

script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://MRxRafi.github.io/CVRafa-FRONT/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/cvrafa-front
  on:
    branch: master
