languaje: node_js
node_js:
- '14'
dist: trusty
sudo: required
branches:
  only:
  - master
before script:
- npm install -g @angular/cli
script:
- ng lint
- npm run test-headless
- ng build --prod
deploy:
  provider: firebase
  token:
    secure: ckTMkVau11pXQB9vQKKdt2GG5FD+MRfJpC+I+CSMu64JT/Xfzo5t80W55axP8D1+nbTHmkiV4AnCFIEW2P5WjCbC67dtdhIa7kLycmSYqzS3udqWluUyr2Byr5f+Ew9AoPtsiNgSxAQq6D2UFgVjflTEpUT/K9L9M0INI1lPWymHr6//xT64hlZJoeGqhCpmAGFfHf9iVtwGtPKBP2yuzl3PepP8mscL+0AZf3skfrcgktUvwpUotDDTrcif6sa2JvErAv49upLZf7Oi+7xPO+tEzmBHi6BFGnO6Cx+yG+YWenqQaXH8SBQlp07P+VkMlDSYATCmMOkXjVDrcHtbF9ZFNO41Kmsf8mBcBmiTekEwP9HfIapwjkRxg+2AdH2RIHZJcFWQGSXcxhT4OfwwI9BUdq1SkEtqkSrOvBgOTZzDC83Vj4HmuI3vSLLfPI3kRAEAPyRZX7RiltN1ouTSTXuOc5JnS1/2b1g2n7hRBdOu0aQRCpFT7R3GtmirKq4hOgBrK/1SLr2X9RERZfBsqiPfNr98tgrTKH7RomVXJKf4hzwfgEZ7nx+1JbYBkINXpMGO2J2jxC1+eZRN8TB6t9N5UGZr+VMJdnYCwoO5r3dru7ww5MzpR5rMvphpgukGPzYSzbc45wr1gP3/UXqwpnaY/8SXdKniAgZ073e7Ihs=
env:
  global:
    secure: ckTMkVau11pXQB9vQKKdt2GG5FD+MRfJpC+I+CSMu64JT/Xfzo5t80W55axP8D1+nbTHmkiV4AnCFIEW2P5WjCbC67dtdhIa7kLycmSYqzS3udqWluUyr2Byr5f+Ew9AoPtsiNgSxAQq6D2UFgVjflTEpUT/K9L9M0INI1lPWymHr6//xT64hlZJoeGqhCpmAGFfHf9iVtwGtPKBP2yuzl3PepP8mscL+0AZf3skfrcgktUvwpUotDDTrcif6sa2JvErAv49upLZf7Oi+7xPO+tEzmBHi6BFGnO6Cx+yG+YWenqQaXH8SBQlp07P+VkMlDSYATCmMOkXjVDrcHtbF9ZFNO41Kmsf8mBcBmiTekEwP9HfIapwjkRxg+2AdH2RIHZJcFWQGSXcxhT4OfwwI9BUdq1SkEtqkSrOvBgOTZzDC83Vj4HmuI3vSLLfPI3kRAEAPyRZX7RiltN1ouTSTXuOc5JnS1/2b1g2n7hRBdOu0aQRCpFT7R3GtmirKq4hOgBrK/1SLr2X9RERZfBsqiPfNr98tgrTKH7RomVXJKf4hzwfgEZ7nx+1JbYBkINXpMGO2J2jxC1+eZRN8TB6t9N5UGZr+VMJdnYCwoO5r3dru7ww5MzpR5rMvphpgukGPzYSzbc45wr1gP3/UXqwpnaY/8SXdKniAgZ073e7Ihs=
