languaje: node_js
node_js:
- '14'
dist: trusty
sudo: required
branches:
  only:
  - master
before script:
- npm install -g @angular/cli
script:
- ng lint
- npm run test-headless
- ng build --prod
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
